#ifndef SVN_DIR_STATUS_H
#define SVN_DIR_STATUS_H

enum path_status {STATUS_NO_CHANGE, STATUS_ADDED, STATUS_CONFLICTED, STATUS_DELETED, STATUS_IGNORED, STATUS_LOCKED, STATUS_MODIFIED, STATUS_NORMAL, STATUS_READONLY, STATUS_UNVERSIONED};

enum path_status svn_get_dir_status(const char *path);

#endif // SVN_DIR_STATUS_H
